### ISSUE TITLE
Opinionated router factory method parameters

### ISSUE THREAD

**Issue by smarki** [akoufatzis/nodejs-app-architecture#1]
As of now the routers' factory methods are opinionated on the expected name of the service provided. 
This hides away implementation requirements on a deeper lvl than needed. 

Ideally services should be passed from the http server's factory as needed by the integrator. 

To elaborate: 
At the moment routers accept {service name} params, making them opinionated on what service they require. That might make the code base difficult to maintain as a simple thing as a refactor would require full knowledge of all implementors to handle correctly. In other words it acts as a hidden requirement that you have to read into to understand.

Where else, if index.js of the http module would delegate the services as needed helps with the transparency and maintenability of the code base.

**Comment by akoufatzis** [comment]
After the migration of the project to typescript this issue was addressed and the router factory methods aren't opinionated anymore
